// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/youxihu/GWatch-new/internal/app/usecase"
	logger3 "github.com/youxihu/GWatch-new/internal/app/usecase/logger"
	monitoring2 "github.com/youxihu/GWatch-new/internal/app/usecase/monitoring"
	"github.com/youxihu/GWatch-new/internal/app/usecase/scheduled_push"
	"github.com/youxihu/GWatch-new/internal/app/usecase/scheduler"
	"github.com/youxihu/GWatch-new/internal/app/usecase/security_monitoring"
	"github.com/youxihu/GWatch-new/internal/domain/collector"
	"github.com/youxihu/GWatch-new/internal/domain/config"
	"github.com/youxihu/GWatch-new/internal/domain/entity/shared"
	"github.com/youxihu/GWatch-new/internal/domain/logger"
	monitoring3 "github.com/youxihu/GWatch-new/internal/domain/monitoring"
	scheduled_push2 "github.com/youxihu/GWatch-new/internal/domain/scheduled_push"
	"github.com/youxihu/GWatch-new/internal/domain/scheduled_push/client"
	"github.com/youxihu/GWatch-new/internal/domain/scheduled_push/common"
	"github.com/youxihu/GWatch-new/internal/domain/scheduled_push/server"
	"github.com/youxihu/GWatch-new/internal/infra/collector/external"
	"github.com/youxihu/GWatch-new/internal/infra/collector/host"
	"github.com/youxihu/GWatch-new/internal/infra/config"
	logger2 "github.com/youxihu/GWatch-new/internal/infra/logger"
	"github.com/youxihu/GWatch-new/internal/infra/monitoring"
	common2 "github.com/youxihu/GWatch-new/internal/infra/scheduled_push/common"
	"os"
	"os/signal"
	"syscall"
)

// Injectors from wire.go:

// InitializeApp 初始化应用程序的所有依赖
func InitializeApp() (*App, error) {
	provider, err := NewConfigProvider()
	if err != nil {
		return nil, err
	}
	config := NewConfig(provider)
	hostCollector := NewHostCollector()
	redisClient := NewRedisCollector(provider)
	httpCollector := NewHTTPCollector(provider)
	evaluator := NewEvaluator(hostCollector)
	alertStateStorage := NewAlertStateStorage()
	basePolicy := NewBasePolicy(alertStateStorage, hostCollector, config)
	formatter := NewMarkdownFormatter()
	notifier := NewDingTalkNotifier(provider)
	alertLogStorage := NewAlertLogStorage()
	loggerFactory := NewLoggerFactory(config)
	logger := NewLogger(loggerFactory)
	baseMonitoringUseCase := NewBaseMonitoringUseCase(hostCollector, redisClient, httpCollector, evaluator, basePolicy, formatter, notifier, alertLogStorage, logger)
	httpPolicy := NewHTTPPolicy(alertStateStorage, hostCollector, config)
	httpMonitoringUseCase := NewHTTPMonitoringUseCase(hostCollector, redisClient, httpCollector, evaluator, httpPolicy, formatter, notifier, alertLogStorage, logger)
	coordinator := NewCoordinator(baseMonitoringUseCase, httpMonitoringUseCase, basePolicy, httpPolicy)
	metricsCollector := NewMetricsCollector(hostCollector, redisClient, httpCollector)
	clientDataRepository := NewClientDataRepository()
	scheduledPushDataLogStorage := NewDataLogStorage()
	clientUseCase := NewClientUseCase(metricsCollector, clientDataRepository, scheduledPushDataLogStorage)
	scheduledPushFormatter := NewScheduledPushFormatter()
	serverUseCase := NewServerUseCase(metricsCollector, clientDataRepository, scheduledPushFormatter, notifier, scheduledPushDataLogStorage)
	scheduledPushUseCase := NewScheduledPushUseCase(clientUseCase, serverUseCase)
	scheduledPushScheduler := NewScheduledPushScheduler(scheduledPushUseCase)
	loggerService := NewLoggerService(logger)
	certificateFetcher := NewCertificateFetcher()
	service := NewSecurityMonitoringService(notifier, alertStateStorage, certificateFetcher)
	app := NewApp(config, coordinator, scheduledPushScheduler, loggerService, alertStateStorage, service)
	return app, nil
}

// wire.go:

// BasePolicy 基础告警策略类型别名
type BasePolicy *monitoring.StatefulPolicy

// HTTPPolicy HTTP告警策略类型别名
type HTTPPolicy *monitoring.StatefulPolicy

// BaseMonitoringUseCase 基础监控用例类型别名
type BaseMonitoringUseCase *monitoring2.MonitoringUseCase

// HTTPMonitoringUseCase HTTP监控用例类型别名
type HTTPMonitoringUseCase *monitoring2.MonitoringUseCase

// ProviderSet 定义所有基础设施提供者
var ProviderSet = wire.NewSet(

	NewConfigProvider,
	NewConfig,

	NewHostCollector,
	NewRedisCollector,
	NewHTTPCollector,

	NewEvaluator,
	NewMarkdownFormatter,

	NewDingTalkNotifier,

	NewAlertLogStorage,

	NewAlertStateStorage,

	NewBasePolicy,
	NewHTTPPolicy,

	NewSystemMetricsService,

	NewBaseMonitoringUseCase,
	NewHTTPMonitoringUseCase,
	NewSecurityMonitoringService,

	NewClientDataRepository,
	NewScheduledPushFormatter,
	NewDataLogStorage,
	NewMetricsCollector,
	NewClientUseCase,
	NewServerUseCase,
	NewCertificateFetcher,
)

// NewConfigProvider 创建配置提供者
func NewConfigProvider() (config.Provider, error) {

	configPath := os.Getenv("GWATCH_CONFIG")
	if configPath == "" {
		configPath = "config/config.yml"
	}
	return configimpl.NewYAMLProvider(configPath)
}

// NewHostCollector 创建主机信息收集器
func NewHostCollector() collector.HostCollector {
	return host.New()
}

// NewRedisCollector 创建 Redis 收集器
func NewRedisCollector(provider config.Provider) usecase.RedisClient {
	return external.NewRedisCollector(provider)
}

// NewHTTPCollector 创建 HTTP 收集器
func NewHTTPCollector(provider config.Provider) collector.HTTPCollector {
	return external.NewHTTPCollector(provider)
}

// NewEvaluator 创建评估器
func NewEvaluator(hostCollector collector.HostCollector) monitoring3.Evaluator {
	evaluator := monitoring.NewSimpleEvaluator()
	evaluator.SetHostCollector(hostCollector)
	return evaluator
}

// NewMarkdownFormatter 创建 Markdown 格式化器
func NewMarkdownFormatter() monitoring3.Formatter {
	return monitoring.NewMarkdownFormatter()
}

// NewDingTalkNotifier 创建钉钉通知器
func NewDingTalkNotifier(provider config.Provider) monitoring3.Notifier {
	return monitoring.NewDingTalkNotifier(provider)
}

// NewAlertLogStorage 创建告警日志存储服务
func NewAlertLogStorage() monitoring3.AlertLogStorage {
	return monitoring.NewAlertLogStorage()
}

// NewAlertStateStorage 创建告警状态存储服务
func NewAlertStateStorage() monitoring3.AlertStateStorage {
	return monitoring.NewAlertStateStorage()
}

// createStatefulPolicy 创建告警策略（公共方法）
func createStatefulPolicy(alertStateStorage monitoring3.AlertStateStorage, hostCollector collector.HostCollector, config2 *entity.Config) *monitoring.StatefulPolicy {
	policy := monitoring.NewStatefulPolicy().(*monitoring.StatefulPolicy)
	policy.SetAlertStateStorage(alertStateStorage)
	policy.SetHostCollector(hostCollector)
	policy.SetConfig(config2)
	return policy
}

// NewBasePolicy 创建基础告警策略
func NewBasePolicy(alertStateStorage monitoring3.AlertStateStorage, hostCollector collector.HostCollector, config2 *entity.Config) BasePolicy {
	return createStatefulPolicy(alertStateStorage, hostCollector, config2)
}

// NewHTTPPolicy 创建 HTTP 告警策略
func NewHTTPPolicy(alertStateStorage monitoring3.AlertStateStorage, hostCollector collector.HostCollector, config2 *entity.Config) HTTPPolicy {
	return createStatefulPolicy(alertStateStorage, hostCollector, config2)
}

// NewBaseMonitoringUseCase 创建基础监控用例
func NewBaseMonitoringUseCase(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
	evaluator monitoring3.Evaluator,
	policy BasePolicy,
	formatter monitoring3.Formatter,
	notifier monitoring3.Notifier,
	alertLogStorage monitoring3.AlertLogStorage,
	log logger.Logger,
) BaseMonitoringUseCase {
	return monitoring2.NewMonitoringUseCase(
		hostInfo,
		redisInfo,
		httpInfo,
		evaluator,
		(*monitoring.StatefulPolicy)(policy),
		formatter,
		notifier,
		alertLogStorage,
		log,
	)
}

// NewHTTPMonitoringUseCase 创建HTTP监控用例
func NewHTTPMonitoringUseCase(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
	evaluator monitoring3.Evaluator,
	policy HTTPPolicy,
	formatter monitoring3.Formatter,
	notifier monitoring3.Notifier,
	alertLogStorage monitoring3.AlertLogStorage,
	log logger.Logger,
) HTTPMonitoringUseCase {
	return monitoring2.NewMonitoringUseCase(
		hostInfo,
		redisInfo,
		httpInfo,
		evaluator,
		(*monitoring.StatefulPolicy)(policy),
		formatter,
		notifier,
		alertLogStorage,
		log,
	)
}

// NewSystemMetricsService 创建系统指标服务
func NewSystemMetricsService(
	hostInfo collector.HostCollector,
	redisInfo usecase.RedisClient,
	httpInfo collector.HTTPCollector,
) *monitoring2.SystemMetricsService {
	return monitoring2.NewSystemMetricsService(hostInfo, redisInfo, httpInfo)
}

// NewCoordinator 创建协调器
func NewCoordinator(
	runnerBase BaseMonitoringUseCase,
	runnerHTTP HTTPMonitoringUseCase,
	policyBase BasePolicy,
	policyHTTP HTTPPolicy,
) *monitoring2.Coordinator {
	return monitoring2.NewCoordinator(
		(*monitoring2.MonitoringUseCase)(runnerBase),
		(*monitoring2.MonitoringUseCase)(runnerHTTP),
		(*monitoring.StatefulPolicy)(policyBase),
		(*monitoring.StatefulPolicy)(policyHTTP),
	)
}

// NewMetricsCollector 创建指标收集器
func NewMetricsCollector(
	hostCollector collector.HostCollector,
	redisClient usecase.RedisClient,
	httpCollector collector.HTTPCollector,
) *scheduled_push.MetricsCollector {
	return scheduled_push.NewMetricsCollector(hostCollector, redisClient, httpCollector)
}

// NewDataLogStorage 创建数据日志存储服务
func NewDataLogStorage() common.ScheduledPushDataLogStorage {
	return common2.NewScheduledPushDataLogStorage()
}

// NewClientUseCase 创建客户端用例
func NewClientUseCase(
	metricsCollector *scheduled_push.MetricsCollector,
	clientDataRepository common.ClientDataRepository,
	dataLogStorage common.ScheduledPushDataLogStorage,
) client.ClientUseCase {
	return scheduled_push.NewClientUseCase(metricsCollector, clientDataRepository, dataLogStorage)
}

// NewServerUseCase 创建服务端用例
func NewServerUseCase(
	metricsCollector *scheduled_push.MetricsCollector,
	clientDataRepository common.ClientDataRepository,
	scheduledPushFormatter common.ScheduledPushFormatter,
	notifier monitoring3.Notifier,
	dataLogStorage common.ScheduledPushDataLogStorage,
) server.ServerUseCase {
	return scheduled_push.NewServerUseCase(metricsCollector, clientDataRepository, scheduledPushFormatter, notifier, dataLogStorage)
}

// NewScheduledPushUseCase 创建全局定时推送用例
func NewScheduledPushUseCase(
	clientUseCase client.ClientUseCase,
	serverUseCase server.ServerUseCase,
) scheduled_push2.ScheduledPushUseCase {
	return scheduled_push.NewScheduledPushUseCase(clientUseCase, serverUseCase)
}

// NewClientDataRepository 创建客户端数据仓库
func NewClientDataRepository() common.ClientDataRepository {
	return common2.NewClientDataRepository()
}

// NewScheduledPushFormatter 创建定时推送格式化器
func NewScheduledPushFormatter() common.ScheduledPushFormatter {
	return common2.NewScheduledPushFormatter()
}

// NewScheduledPushScheduler 创建全局定时推送调度器
func NewScheduledPushScheduler(scheduledPushUseCase scheduled_push2.ScheduledPushUseCase) scheduled_push2.ScheduledPushScheduler {
	return scheduler.NewScheduledPushScheduler(scheduledPushUseCase)
}

// NewLoggerFactory 创建日志工厂
func NewLoggerFactory(config2 *entity.Config) logger.LoggerFactory {
	return logger2.NewLoggerFactory(&config2.Log)
}

// NewLogger 创建日志器
func NewLogger(factory logger.LoggerFactory) logger.Logger {
	l, err := factory.CreateLogger()
	if err != nil {

		return logger2.NewConsoleLogger()
	}
	return l
}

// NewLoggerService 创建日志服务
func NewLoggerService(l logger.Logger) *logger3.LoggerService {
	return logger3.NewLoggerService(l)
}

// App 应用程序结构体，包含所有需要的组件
type App struct {
	Config                 *entity.Config
	Coordinator            *monitoring2.Coordinator
	ScheduledPushScheduler scheduled_push2.ScheduledPushScheduler
	LoggerService          *logger3.LoggerService
	AlertStateStorage      monitoring3.AlertStateStorage // 告警状态存储（用于退出时关闭连接）
	SecurityMonitor        *security_monitoring.Service
}

// Start 启动应用程序
func (app *App) Start() error {

	if app.Config.ScheduledPush != nil && app.Config.ScheduledPush.Enabled {
		mode := app.Config.ScheduledPush.Mode
		if mode == "client" {
			logger2.Info("Client模式开始监控...")
		} else if mode == "server" {
			logger2.Info("Server模式开始监控...")
		} else {
			logger2.Info("开始监控...")
		}
	} else {
		logger2.Info("开始监控...")
	}

	app.printMonitoringStatus()

	stopCh := make(chan struct{})
	go app.handleSignals(stopCh)

	if err := app.startSchedulers(stopCh); err != nil {
		return err
	}

	app.Coordinator.RunWithIntervals(app.Config, stopCh)
	logger2.Info("GWatch 正在退出...")
	app.cleanup()
	return nil
}

// cleanup 清理资源
func (app *App) cleanup() {

	if app.AlertStateStorage != nil {
		if err := app.AlertStateStorage.Close(); err != nil {
			logger2.Warnf("关闭告警状态存储连接失败: %v", err)
		} else {
			logger2.Info("已关闭告警状态存储连接")
		}
	}
}

// printMonitoringStatus 打印监控状态
func (app *App) printMonitoringStatus() {
	cfg := app.Config

	if cfg.HostMonitoring != nil && cfg.HostMonitoring.Enabled {
		logger2.Infof("主机监控已启用，监控间隔: %v", cfg.HostMonitoring.CollectInterval)
	} else if cfg.HostMonitoring != nil && !cfg.HostMonitoring.Enabled {
		logger2.Info("主机监控已禁用")
	}

	if cfg.AppMonitoring != nil && cfg.AppMonitoring.Enabled {
		logger2.Info("应用层监控已启用")
		if cfg.AppMonitoring.Redis != nil && cfg.AppMonitoring.Redis.Enabled {
			logger2.Info("  - Redis监控已启用")
		} else if cfg.AppMonitoring.Redis != nil && !cfg.AppMonitoring.Redis.Enabled {
			logger2.Info("  - Redis监控已禁用")
		}
	} else if cfg.AppMonitoring != nil && !cfg.AppMonitoring.Enabled {
		logger2.Info("应用层监控已禁用")
	}

	if cfg.HTTPMonitoring != nil && cfg.HTTPMonitoring.Enabled {
		logger2.Info("HTTP接口监控已启用")
	} else if cfg.HTTPMonitoring != nil && !cfg.HTTPMonitoring.Enabled {
		logger2.Info("HTTP接口监控已禁用")
	}

	if cfg.CertificateExpirationMonitoring != nil && cfg.CertificateExpirationMonitoring.Enabled {
		logger2.Info("HTTPS证书过期监控已启用")
	} else if cfg.CertificateExpirationMonitoring != nil && !cfg.CertificateExpirationMonitoring.Enabled {
		logger2.Info("HTTPS证书过期监控已禁用")
	}
}

// handleSignals 处理系统信号
func (app *App) handleSignals(stopCh chan struct{}) {
	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	sig := <-c
	logger2.Infof("接收到信号 %v，正在优雅退出...", sig)
	close(stopCh)
}

// startSchedulers 启动所有调度器
func (app *App) startSchedulers(stopCh <-chan struct{}) error {
	cfg := app.Config

	if cfg.ScheduledPush != nil && cfg.ScheduledPush.Enabled {
		logger2.Info("启动全局定时推送调度器...")
		if err := app.ScheduledPushScheduler.Start(cfg, stopCh); err != nil {
			logger2.Errorf("启动全局定时推送调度器失败: %v", err)
			return err
		}
	}

	if app.SecurityMonitor != nil {
		if err := app.SecurityMonitor.Start(cfg, stopCh); err != nil {
			logger2.Errorf("启动安全监控调度器失败: %v", err)
			return err
		}
	}

	return nil
}

// NewApp 创建应用程序实例
func NewApp(config2 *entity.Config,
	coordinator *monitoring2.Coordinator,
	scheduledPushScheduler scheduled_push2.ScheduledPushScheduler,
	loggerService *logger3.LoggerService,
	alertStateStorage monitoring3.AlertStateStorage,
	securityMonitor *security_monitoring.Service,
) *App {
	return &App{
		Config:                 config2,
		Coordinator:            coordinator,
		ScheduledPushScheduler: scheduledPushScheduler,
		LoggerService:          loggerService,
		AlertStateStorage:      alertStateStorage,
		SecurityMonitor:        securityMonitor,
	}
}

func NewSecurityMonitoringService(
	notifier monitoring3.Notifier,
	alertStateStorage monitoring3.AlertStateStorage,
	certFetcher monitoring3.CertificateFetcher,
) *security_monitoring.Service {
	return security_monitoring.NewService(notifier, alertStateStorage, certFetcher)
}

// NewCertificateFetcher 证书拉取器
func NewCertificateFetcher() monitoring3.CertificateFetcher {
	return monitoring.NewTLSCertificateFetcher()
}

// NewConfig 从配置提供者获取配置
func NewConfig(provider config.Provider) *entity.Config {
	return provider.GetConfig()
}
